<div class="gdlr-core-pbf-wrapper " style="padding: 0px 0px 0px 0px;">
    <div class="gdlr-core-pbf-background-wrap" style="background-color: #282828 ;"></div>
    <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
        <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-pbf-wrapper-full-no-space">
            <div class="gdlr-core-pbf-element">
                <div class="gdlr-core-revolution-slider-item gdlr-core-item-pdlr gdlr-core-item-pdb " style="padding-bottom: 0px;">
                    <link href="https://fonts.googleapis.com/css?family=Raleway:200" rel="stylesheet" property="stylesheet" type="text/css" media="all">
                    <div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
                        <div id="rev_slider_1_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8">
                            <ul>
                                <li data-index="rs-2" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="assets/upload/slider-2-1-100x50.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description=""> <img src="assets/upload/slider-2-1.jpg" alt="" title="slider-2" width="1800" height="1000" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-2-layer-12" data-x="16" data-y="center" data-voffset="11" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;"><img src="assets/upload/slider-2-1-1.png" alt="" data-ww="359px" data-hh="315px" width="359" height="315" data-no-retina></div>
                                    <div class="tp-caption   tp-resizeme" id="slide-2-layer-5" data-x="right" data-hoffset="14" data-y="center" data-voffset="-95" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":300,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 110px; line-height: auto; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Nunito;text-transform:uppercase;">L’@gence Com</div>
                                    <div class="tp-caption   tp-resizeme" id="slide-2-layer-6" data-x="right" data-hoffset="89" data-y="center" data-voffset="-18" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":480,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 40px; line-height: autopx; font-weight: 200; color: #ffffff; letter-spacing: 0px;font-family:Raleway;"> Conseil en Marketing & Communication</div>
                                    <div class="tp-caption   tp-resizeme" id="slide-2-layer-10" data-x="right" data-hoffset="30" data-y="center" data-voffset="64" data-width="['768']" data-height="['55']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":650,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; min-width: 768px; max-width: 768px; max-width: 55px; max-width: 55px; white-space: normal; font-size: 17px; line-height: 27px; font-weight: 400; color: #ffffff; letter-spacing: 0px;font-family:Poppins;"> Agence de conseil, création et communication Web en Tunisie</div>
                                    <div class="tp-caption rev-btn rev-withicon " id="slide-2-layer-13" data-x="right" data-hoffset="434" data-y="center" data-voffset="152" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":920,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,1);bg:rgba(255,255,255,1);bs:solid;bw:0px 0px -1px 0px;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[18,18,18,18]" data-paddingright="[37,37,37,37]" data-paddingbottom="[19,19,19,19]" data-paddingleft="[37,37,37,37]" style="z-index: 9; white-space: nowrap; font-size: 12px; line-height: 17px; font-weight: 700; color: rgba(255,255,255,1); letter-spacing: 1px;font-family:Poppins;text-transform:uppercase;background-color:rgb(129,202,65);border-color:rgb(255,255,255);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;"> APPELEZ-NOUS (+216) 54 011 609</div>
                                    <a href="{{ route('contact.index') }}" class="tp-caption rev-btn rev-withicon " id="slide-2-layer-7" data-x="right" data-hoffset="225" data-y="center" data-voffset="152" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":920,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,1);bg:rgba(255,255,255,1);"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[16,16,16,16]" data-paddingright="[35,35,35,35]" data-paddingbottom="[17,17,17,17]" data-paddingleft="[35,35,35,35]" style="z-index: 10; white-space: nowrap; font-size: 12px; line-height: 17px; font-weight: 700; color: rgba(255,255,255,1); letter-spacing: 1px;font-family:Poppins;text-transform:uppercase;border-color:rgb(255,255,255);border-style:solid;border-width:2px 2px 2px 2px;border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;"> Nous contacter
                                    </a>
                                </li>
                                <li data-index="rs-3" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="https://cdn.goodlayers.com/seocrawler/demo2/wp-content/uploads/2017/06/port-item-5-bg-100x50.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description=""> <img src="https://cdn.goodlayers.com/seocrawler/demo2/wp-content/uploads/2017/06/port-item-5-bg.jpg" alt="" title="port-item-5-bg" width="1800" height="800" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-3-layer-12" data-x="center" data-hoffset="" data-y="center" data-voffset="-110" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;"><img src="assets/upload/slider-3-3-1.png" alt="" data-ww="305px" data-hh="282px" width="305" height="282" data-no-retina></div>
                                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-3-layer-14" data-x="178" data-y="center" data-voffset="-24" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;"><img src="assets/upload/slider-3-1-1.png" alt="" data-ww="126px" data-hh="108px" width="126" height="108" data-no-retina></div>
                                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-4" id="slide-3-layer-16" data-x="right" data-hoffset="149" data-y="center" data-voffset="-40" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7;"><img src="assets/upload/slider-3-2-1.png" alt="" data-ww="186px" data-hh="151px" width="186" height="151" data-no-retina></div>
                                    <div class="tp-caption   tp-resizeme" id="slide-3-layer-5" data-x="center" data-hoffset="" data-y="center" data-voffset="38" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":300,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; white-space: nowrap; font-size: 110px; line-height: autopx; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Nunito;text-transform:uppercase;"> L’@gence Com</div>
                                    <div class="tp-caption   tp-resizeme" id="slide-3-layer-6" data-x="center" data-hoffset="" data-y="center" data-voffset="109" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":480,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; white-space: nowrap; font-size: 50px; line-height: autopx; font-weight: 200; color: #ffffff; letter-spacing: 0px;font-family:Raleway;"> Agence de conseil, création et communication</div>
                                    <div class="tp-caption rev-btn rev-withicon " id="slide-3-layer-13" data-x="center" data-hoffset="-80" data-y="center" data-voffset="192" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":920,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,1);bg:rgba(255,255,255,1);bs:solid;bw:0px 0px -1px 0px;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[18,18,18,18]" data-paddingright="[37,37,37,37]" data-paddingbottom="[19,19,19,19]" data-paddingleft="[37,37,37,37]" style="z-index: 10; white-space: nowrap; font-size: 12px; line-height: 17px; font-weight: 700; color: #3a3a3a; letter-spacing: 1px;font-family:Poppins;text-transform:uppercase;background-color:rgb(255,255,255);border-color:rgb(255,255,255);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;"> APPELEZ-NOUS (+216) 54 011 609</div>
                                    <div class="tp-caption rev-btn rev-withicon " id="slide-3-layer-7" data-x="center" data-hoffset="175" data-y="center" data-voffset="192" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":920,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,1);bg:rgba(255,255,255,1);"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[16,16,16,16]" data-paddingright="[35,35,35,35]" data-paddingbottom="[17,17,17,17]" data-paddingleft="[35,35,35,35]" style="z-index: 11; white-space: nowrap; font-size: 12px; line-height: 17px; font-weight: 700; color: rgba(255,255,255,1); letter-spacing: 1px;font-family:Poppins;text-transform:uppercase;border-color:rgb(255,255,255);border-style:solid;border-width:2px 2px 2px 2px;border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;"> nous contacter</div>
                                </li>
                            </ul>
                            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>